name: cladvpn_service
description: A plugin that allow you to connect OpenVPN service with Flutter
version: 1.2.0
homepage: https://github.com/repfly/openvpn_flutter
publish_to: 'none'


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter 

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
    
flutter:
  plugin:
    platforms:
      android:
        package: id.laskarmedia.openvpn_flutter
        pluginClass: OpenVPNFlutterPlugin
      ios:
        pluginClass: OpenVPNFlutterPlugin
